version: "2"
services:
  root:
    build:
      context: .
    volumes:
      - .:/node
      - ./configs/supervisor/conf.d:/etc/supervisor/conf.d
    ports:
      - 93:80
    environment:
      - NODE_ROLE=root
    command: /node/sw-node
  host:
    image: spiderweb_root
    volumes:
      - .:/node
      - ./configs/supervisor/conf.d:/etc/supervisor/conf.d
    ports:
      - 94:80
    environment:
      - ROOT_ADDR=root
    depends_on:
      - root
    command: /node/sw-node
