version: "2"
services:
  spiderweb.com:
    build:
      context: docker
    image: spiderweb.com
    volumes:
      - ./sw-node:/usr/bin/sw-node
      - ./docker/configs/supervisor/conf.d:/etc/supervisor/conf.d
    ports:
      - 93:80
    expose:
      - 80
      - 22
    environment:
      - NODE_ROLE=root
  registry:
    image: spiderweb.com
    volumes:
      - ./sw-node:/usr/bin/sw-node
      - ./docker/configs/supervisor/conf.d:/etc/supervisor/conf.d
    ports:
      - 94:80
    expose:
      - 80
      - 22
    environment:
      - ROOT_ADDR=root
    depends_on:
      - spiderweb.com
