version: "2"
services:
  spiderweb.com:
    build:
      context: docker
    volumes:
      - .:/node
      - ./configs/supervisor/conf.d:/etc/supervisor/conf.d
    ports:
      - 93:80
    expose:
      - 80
      - 22
    environment:
      - NODE_ROLE=root
    command: "/node/sw-node"
  registry:
    image: spiderweb_spiderweb.com
    volumes:
      - .:/node
      - ./configs/supervisor/conf.d:/etc/supervisor/conf.d
    ports:
      - 94:80
    expose:
      - 80
      - 22
    environment:
      - ROOT_ADDR=root
    depends_on:
      - spiderweb.com
    command: sh -c "sleep 1 && /node/sw-node"
